export const SIGN_IN_SUCCEED = 'SIGN_IN_SUCCEED';
export const UPDATE_ROUTE = 'UPDATE_ROUTE';

export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const SET_SEARCH = 'SET_SEARCH';
export const SET_IN_DETAIL = 'SET_IN_DETAIL';
export const SELECT_EVENT = 'SELECT_EVENT';
